# ==================================================================================================================== #
#                                                EXPERIMENT CONFIGURATION                                              # 
# ==================================================================================================================== #


project:
    name: InterAct-combinedsocial    # interact, InterAct-combinedsocial 
    version: 1.0.0
    description: architecture for modelling person gaze and gesture behaviour, and interactions

# ------------------------------------------------------------------------------------------------------------------- #

experiment:
    name: MTGS-FT-childplay #rinn-hgaze-n1-multivit-gaze_vec-ep15-amp
    group: null # /!\
    task: test # combination of {train, val, test, predict} separated by '+' sign. TODO: train+predict # /!\
    dataset: childplay # /!\ gazefollow, childplay, videoattentiontarget, videocoatt, uco_laeo, combined_social, vacation
    path: ${hydra:runtime.cwd} # to retrieve logs and checkpoints

# ------------------------------------------------------------------------------------------------------------------- #

data:
    num_samples: 36000    # GazeFollow: 108955, VAT: 9000, childplay: 15000, combined_social: 36000, laeo: 2900
    num_people: 4 # /!\ int or -1 for all
    return_depth: False # /!\
    return_head_mask: False # /!\
    image_size: 224 # /!\ used only for scene tokenizer
    heatmap_size: 64
    heatmap_sigma: 3
    temporal_context: 2    # 2; temporal context window # frames
    temporal_stride: 3    # 3; temporal stride for model input
    vlm_dim: 24    # ava: 24, swig:406, hico:117 dimension of VLM context vector
    gf:
        root: /idiap/resource/database/gazefollow_extended
        root_depth: /idiap/temp/stafasca/data/GazeFollow-depth
    coatt:
        root: /idiap/resource/database/VideoCoAtt_Dataset
    vat:
        root: /idiap/resource/database/VideoAttentionTarget
    laeo:
        root: /idiap/home/nchutisilp/UCO-LAEO/
    childplay:
        root: /idiap/temp/stafasca/data/ChildPlay
        root_depth: None
        root_focal: None
    vacation:
        root: /idiap/temp/agupta/data/VACATION

# ------------------------------------------------------------------------------------------------------------------- #

model:
    model_name: 'gaze_interact'    # {sharingan_social, gaze_interact, geom_gaze}
    sharingan:
        output: heatmap    # heatmap, point
        patch_size: 16
        token_dim: 768
        image_size: ${data.image_size} # /!\
        gaze_feature_dim: 512
        encoder_depth: 12
        encoder_num_heads: 12
        encoder_num_global_tokens: 1
        encoder_mlp_ratio: 4.0
        encoder_use_qkv_bias: True
        encoder_drop_rate: 0.0
        encoder_attn_drop_rate: 0.0
        encoder_drop_path_rate: 0.0
        decoder_feature_dim: 128
        decoder_hooks: [2, 5, 8, 11]
        decoder_hidden_dims: [96, 192, 384, 768]
        decoder_use_bn: True
        gaze_weights: /idiap/temp/stafasca/weights/gaze/gaze360_resnet18.pt
        multivit_weights: /idiap/temp/stafasca/projects/sharingan/weights/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c.pth
        # multivit_weights: False
    weights: False # {False, path to weights}
#     weights: /idiap/temp/stafasca/projects/sharingan/experiments/2023-03-02/23-23-45/checkpoints/best.ckpt # Sharingan GF weights
#     weights: /idiap/temp/agupta/src/rinnegan-master/experiments/2024-01-12/18-13-51 # Sharingan-social VACATION weights
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2023-11-14/15-43-54/checkpoints/best.ckpt # GF weights
    # weights: /remote/idiap.svm/user.active/agupta/gaze_interact/experiments/2025-01-29/16-55-39/checkpoints/best.ckpt # GF weights, DINO
    # weights: /remote/idiap.svm/user.active/agupta/gaze_interact/experiments/2025-01-30/11-39-25/checkpoints/best.ckpt # GF weights, DINO-448
    # weights: /remote/idiap.svm/temp.perception02/agupta/gaze_interact/experiments/2025-02-28/15-11-46/checkpoints/best.ckpt # GF weights, DINO-noinjector-448
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-14/11-54-57/checkpoints/best.ckpt # GF weights, HICO
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2023-11-16/00-36-14/checkpoints/best.ckpt # GF weights, no GF loss
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2023-11-16/00-36-40/checkpoints/best.ckpt # GF weights, no social
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-10/23-02-26/checkpoints/best.ckpt # GF weights, no social interaction module
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-10/23-02-03/checkpoints/best.ckpt # GF weights, no SP interaction module
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-10/23-01-46/checkpoints/best.ckpt # GF weights, no PS interaction module
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-11/13-37-33/checkpoints/best.ckpt # GF weights, no DPT module
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-05/14-43-57/checkpoints/best.ckpt # CS weights, no spk, no social
#     weights: /idiap/temp/agupta/src/gaze_interact/experiments/2023-11-16/17-19-38/checkpoints/best.ckpt # CS weights; no spk
#     weights: /idiap/temp/agupta/src/rinnegan-master/experiments/2023-11-16/17-19-10/checkpoints/best.ckpt # CS weights; spk

# ------------------------------------------------------------------------------------------------------------------- #

optimizer:
    type: AdamW # not used
    lr: 1e-6 # /!\ 3e-6 (default)
    weight_decay: 1e-3 # /!\

# ------------------------------------------------------------------------------------------------------------------- #

scheduler:
    type: CosineAnnealingWarmRestarts # {CosineAnnealingWarmRestarts, StepLR}
    warmup_epochs: 4 # /!\
    t_0_epochs: 20 # /!\
    t_mult: 1 # /!\

# ------------------------------------------------------------------------------------------------------------------- #

train: 
    seed: 101 # /!\
    matmul_precision: medium # /!\ highest (default), high, medium
    precision: bf16-mixed # /!\ 64 (double), 32 (full), 16 (16bit mixed), bf16-mixed (bfloat16 mixed). Defaults to 32.
    epochs: 20 # /!\
    batch_size: 8 # /!\
    accumulate_grad_batches: 1 # /!\
    device: cuda
    resume: False
    resume_from: /idiap/temp/agupta/src/gaze_interact/checkpoints/last.ckpt
    freeze:
        gaze_encoder: False  # /!\
        gaze_encoder_backbone: False # /!\
        image_tokenizer: True  # /!\
        depth_tokenizer: False  # /!\
        vit_encoder: True  # /!\
        vit_adaptor: False  # /!\
        gaze_decoder: False  # /!\
        inout_decoder: False  # /!\
    swa:
        use: True # /!\
        lr: [1e-6, 1e-6, 1e-6, 1e-6, 3e-7] # /!\ {1e-6, [3e-6, 3e-6, 1e-6]} float, or list of floats for each param group in optimizer
        epoch_start: 12 # /!\
        annealing_epochs: 6 # /!\

# ------------------------------------------------------------------------------------------------------------------- #

val: 
    checkpoint: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-06/14-17-21/checkpoints/best.ckpt
    batch_size: 8 # /!\
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

test:
    checkpoint: "/remote/idiap.svm/temp.perception02/agupta/src/gaze_interact/experiments/2024-03-06/10-24-16/checkpoints/best.ckpt"
    batch_size: 1 # /!\
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

predict:
    root: ../../../demo
    checkpoint: null
    batch_size: 1
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

wandb:
    log: True # /!\
    watch: null # /!\ null, gradients, parameters, all
    watch_freq: 500

# ------------------------------------------------------------------------------------------------------------------- #

hydra: 
    run: 
        dir: ./
    job: 
        chdir: True
