# ==================================================================================================================== #
#                                                EXPERIMENT CONFIGURATION                                              # 
# ==================================================================================================================== #


project:
    name: MTGS-extension    # interact, InterAct-combinedsocial 
    version: 1.0.0
    description: architecture for modelling person gaze and gesture behaviour, and interactions

# ------------------------------------------------------------------------------------------------------------------- #

experiment:
    name: MTGS-NK #rinn-hgaze-n1-multivit-gaze_vec-ep15-amp
    group: null # /!\
    task: test # combination of {train, val, test, predict} separated by '+' sign. TODO: train+predict # /!\
    # dataset: combined_social # /!\ gazefollow, childplay, videoattentiontarget, videocoatt, uco_laeo, combined_social, vacation
    # dataset: videocoatt # /!\ gazefollow, childplay, videoattentiontarget, videocoatt, uco_laeo, combined_social, vacation
    # dataset: childplay # /!\ gazefollow, childplay, videoattentiontarget, videocoatt, uco_laeo, combined_social, vacation
    dataset: videoattentiontarget # /!\ gazefollow, childplay, videoattentiontarget, videocoatt, uco_laeo, combined_social, vacation
    # dataset: uco_laeo # /!\ gazefollow, childplay, videoattentiontarget, videocoatt, uco_laeo, combined_social, vacation
    path: ${hydra:runtime.cwd} # to retrieve logs and checkpoints
    cuda: 6

# ------------------------------------------------------------------------------------------------------------------- #

data:
    num_samples: 36000    # GazeFollow: 108955, VAT: 9000, childplay: 15000, combined_social: 36000, laeo: 2900
    # num_people: 39 # /!\ int or -1 for all
    num_people: all # /!\ int or -1 for all
    num_coatt: 40
    return_depth: False # /!\
    return_head_mask: False # /!\
    image_size: 224 # /!\ used only for scene tokenizer
    heatmap_size: 64
    heatmap_sigma: 3
    # temporal_context: 2    # 2; temporal context window # frames
    temporal_context: 0    # 2; temporal context window # frames
    temporal_stride: 3    # 3; temporal stride for model input
    vlm_dim: 24    # ava: 24, swig:406, hico:117 dimension of VLM context vector
    gf:
        root: /home-local/nakatani/dataset/gazefollow_extended
        root_depth: None
        root_focal: None
    coatt:
        root: data/VideoCoAtt_Dataset
    vat:
        root: /home-local/nakatani/dataset/videoattentiontarget
    laeo:
        root: /home-local/nakatani/dataset/ucolaeodb/
    childplay:
        root: /home-local/nakatani/dataset/ChildPlay-gaze
        root_depth: None
        root_focal: None
    # vacation:
    #     root: /idiap/temp/agupta/data/VACATION

# ------------------------------------------------------------------------------------------------------------------- #

model:
    model_name: 'gaze_interact'    # {sharingan_social, gaze_interact, geom_gaze}
    sharingan:
        output: heatmap    # heatmap, point
        patch_size: 16
        token_dim: 768
        image_size: ${data.image_size} # /!\
        gaze_feature_dim: 512
        encoder_depth: 12
        encoder_num_heads: 12
        encoder_num_global_tokens: 1
        encoder_mlp_ratio: 4.0
        encoder_use_qkv_bias: True
        encoder_drop_rate: 0.0
        encoder_attn_drop_rate: 0.0
        encoder_drop_path_rate: 0.0
        decoder_feature_dim: 128
        decoder_hooks: [2, 5, 8, 11]
        decoder_hidden_dims: [96, 192, 384, 768]
        decoder_use_bn: True
        gaze_weights: /home/nakatani/joint_attention_project/mtgs/src/weights/gaze360_resnet18.pt
        # multivit_weights: /home/nakatani/joint_attention_project/mtgs/src/weights/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c.pth
        # multivit_weights: /home/nakatani/joint_attention_project/mtgs/src/weights/multimae-b_98_rgb+-depth-semseg_1600e_timm-bafa5499.pth
        multivit_weights: False
    interact:
        # person_token_type: normal # {normal, w_gaze_hm, w_gaze_vec}
        person_token_type: normal
    # coatt_hm_type: hm # {coef, hm, coef_iter}
    # coatt_hm_type: coef # {coef, hm, coef_iter}
    coatt_hm_type: coef_iter # {coef, hm, coef_iter}
    # coatt_coef_iter_cnt: 1
    coatt_coef_iter_cnt: 3
    coatt_coatt_layer: self
    coatt_person_layer: sep
    weights: False # {False, path to weights}

# ------------------------------------------------------------------------------------------------------------------- #

optimizer:
    type: AdamW # not used
    lr: 1e-6 # /!\ 3e-6 (default)
    weight_decay: 1e-3 # /!\

# ------------------------------------------------------------------------------------------------------------------- #

scheduler:
    type: CosineAnnealingWarmRestarts # {CosineAnnealingWarmRestarts, StepLR}
    warmup_epochs: 4 # /!\
    t_0_epochs: 20 # /!\
    t_mult: 1 # /!\

# ------------------------------------------------------------------------------------------------------------------- #

train: 
    seed: 101 # /!\
    matmul_precision: medium # /!\ highest (default), high, medium
    precision: bf16-mixed # /!\ 64 (double), 32 (full), 16 (16bit mixed), bf16-mixed (bfloat16 mixed). Defaults to 32.
    epochs: 20 # /!\
    batch_size: 8 # /!\
    accumulate_grad_batches: 1 # /!\
    device: cuda
    resume: False
    resume_from: /idiap/temp/agupta/src/gaze_interact/checkpoints/last.ckpt
    freeze:
        gaze_encoder: False  # /!\
        gaze_encoder_backbone: False # /!\
        image_tokenizer: True  # /!\
        depth_tokenizer: False  # /!\
        vit_encoder: True  # /!\
        vit_adaptor: False  # /!\
        gaze_decoder: False  # /!\
        inout_decoder: False  # /!\
    swa:
        use: True # /!\
        lr: [1e-6, 1e-6, 1e-6, 1e-6, 3e-7] # /!\ {1e-6, [3e-6, 3e-6, 1e-6]} float, or list of floats for each param group in optimizer
        epoch_start: 12 # /!\
        annealing_epochs: 6 # /!\

# ------------------------------------------------------------------------------------------------------------------- #

val: 
    checkpoint: /idiap/temp/agupta/src/gaze_interact/experiments/2024-03-06/14-17-21/checkpoints/best.ckpt
    batch_size: 8 # /!\
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

test:
    # [iter=1]
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-24/11-42-44_COA_True_SOC_False/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-24/11-42-44_COA_True_SOC_False/last.ckpt"
    # [iter=4]
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-24/11-45-22_COA_True_SOC_False/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-24/11-45-22_COA_True_SOC_False/last.ckpt"

    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-26/10-24-24_COA_False_SOC_True/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-26/10-24-24_COA_False_SOC_True/last.ckpt"

    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-26/10-24-42_COA_True_SOC_True/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-10-26/10-24-42_COA_True_SOC_True/last.ckpt"

    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-12/10-18-13_COA_True_SOC_True_coatt_hm_coef/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-12/10-24-22_COA_False_SOC_True_coatt_hm_coef/best.ckpt"

    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-13/13-49-02_COA_True_SOC_True_coatt_hm_coef_iter/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-13/13-49-02_COA_True_SOC_True_coatt_hm_coef_iter/last.ckpt"

    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-13/22-25-17_COA_True_SOC_True_coatt_hm_coef/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-13/22-25-17_COA_True_SOC_True_coatt_hm_coef/last.ckpt"

    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-15/09-24-55_COA_True_SOC_True_coatt_hm_coef_iter/best.ckpt"
    # checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-15/09-24-55_COA_True_SOC_True_coatt_hm_coef_iter/last.ckpt"

    checkpoint: "/home/nakatani/joint_attention_project/mtgs/checkpoints/combined_social/2025-11-17/11-31-47_COA_True_SOC_True_coatt_hm_coef_iter_3/last.ckpt"

    batch_size: 1 # /!\
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

predict:
    root: ../../../demo
    checkpoint: null
    batch_size: 1
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

wandb:
    log: True # /!\
    watch: null # /!\ null, gradients, parameters, all
    watch_freq: 500

# ------------------------------------------------------------------------------------------------------------------- #

hydra: 
    run: 
        dir: ./
    job: 
        chdir: True
